stages:
  - bundle
  - release_generated_build

bundle:
  stage: bundle
  image: node:9.0.0
  only:
    - tags
  script:
    # Install ssh-agent through openssh-client if not present
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    # Add the private key to this user
    - eval $(ssh-agent -s) && ssh-add <(echo "$DEPLOY_PRIVATE_KEY") && mkdir -p ~/.ssh
    - yarn
    - yarn build
    - mkdir temp
    - cd temp
    - git clone -b ci-test-branch https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/crypto_project/frontend/storybook
    - cd storybook && cp -r ../../dist . && cp -r ../../package.json .
    - git config user.email "anibaka9@gmail.com"
    - git config user.name "anibaka"
    - git add .
    - git commit -m "test push"
    - git push https://anibaka:xM7YPi69yMJs4T6FXvHd@gitlab.com/crypto_project/frontend/storybook HEAD:ci-test-branch
  artifacts:
    paths:
    - ./dist