variables:
  DEPLOY_PRIVATE_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA41AQdCY6Rk3WoxYl2Qp1VRUMSVMW7qzBBNfESfZ5jxBtRJ+4iqgW
i/Dpd3Bcqpr+xptrkzeDh7dhiotN9j6cot1qsn1Y3Pohz0p8CxNrRCw+SDrX+kSo+GMkAh
tz0cAQ2JzWVOwC0hZouKUlQpWsQ+xy5UBAQyCC/jDfXDAIOFDvy0oYq9VMt8FJeSaK1Ak0
0sdULRIPxageEcLsqiypGtHmIaHXM5VZS4eN23bJP44kEaiSX4TPzzrh2PBcBbC1H0+jUs
gKFSI4WweI5TiSNFnZcQ42nHT/0yy4czGCeBaMxSv4qY0a6W/4OZHgGDdDk3ESAnz/Xl6K
pKaPbLqOOMaoEXaAyeq5voGidcNf1efCfrzwKIbH9UO0yyuKpnNNUBvN3kdn7lpKEsVmno
mBSAorzt/808FHnTeK9pXEBkRDQDddrL6aH1H6AuA23T2q7TNJ8weIZ7gujdrOoJ1Sz2xa
OboJ6eBYb5J7qeMPbZ41SOWmzwx35Qvn2UiMHjUD9Jj5udbN9co/7NSZwlhJxL/L8cPItB
cQQXAgu0stKc2QphDrq00VJM9QZaA4JfZPp5GF45i8QNzbBuTFPaZnOPm4GS6qGbFmR6X6
MriOyrW7B6T74rPwBaqayGJb0O4uFgQvZSm9K92Q+kS6ULNsJLbF//iE2otjWj0Z1a45W2
UAAAdIR1VsoEdVbKAAAAAHc3NoLXJzYQAAAgEA41AQdCY6Rk3WoxYl2Qp1VRUMSVMW7qzB
BNfESfZ5jxBtRJ+4iqgWi/Dpd3Bcqpr+xptrkzeDh7dhiotN9j6cot1qsn1Y3Pohz0p8Cx
NrRCw+SDrX+kSo+GMkAhtz0cAQ2JzWVOwC0hZouKUlQpWsQ+xy5UBAQyCC/jDfXDAIOFDv
y0oYq9VMt8FJeSaK1Ak00sdULRIPxageEcLsqiypGtHmIaHXM5VZS4eN23bJP44kEaiSX4
TPzzrh2PBcBbC1H0+jUsgKFSI4WweI5TiSNFnZcQ42nHT/0yy4czGCeBaMxSv4qY0a6W/4
OZHgGDdDk3ESAnz/Xl6KpKaPbLqOOMaoEXaAyeq5voGidcNf1efCfrzwKIbH9UO0yyuKpn
NNUBvN3kdn7lpKEsVmnomBSAorzt/808FHnTeK9pXEBkRDQDddrL6aH1H6AuA23T2q7TNJ
8weIZ7gujdrOoJ1Sz2xaOboJ6eBYb5J7qeMPbZ41SOWmzwx35Qvn2UiMHjUD9Jj5udbN9c
o/7NSZwlhJxL/L8cPItBcQQXAgu0stKc2QphDrq00VJM9QZaA4JfZPp5GF45i8QNzbBuTF
PaZnOPm4GS6qGbFmR6X6MriOyrW7B6T74rPwBaqayGJb0O4uFgQvZSm9K92Q+kS6ULNsJL
bF//iE2otjWj0Z1a45W2UAAAADAQABAAACABfnl5NfYcl67hOAhMJqYyRrbjtXzZWT/Uhx
GGde0DHHXHZXBaUvQA+/ag3xdw1J93kTZyC4OdDP7CYRuEUpGHfYKRxUKkAy3dNa1eikRi
eJL5OQ/J2JEuvsISFHmcp5FExzUebkWveU+7ZPR7fU3aTW/M43D4r/pEbvBM5BDtw9Rrpu
NGH9sG+yl/Nxpi/eN/vikmua9qWmpGLhyNmskKwNXtIyntsB3b4fpz9pIojYfdqNi7cX1H
LKkm2p+UNv7dw5F8fg2Y6XZq3MAQ16AYYX3NIS2JNjinO+xDb5Aet3E564nRHXkPjzmXsU
aCijxyt+PJKeaoyWDKZ8DaE1jTcggbpctgBdz0WmjN9TJYK6Lm/yc0XkhSYk7Y96zYExQn
H6PA2MtMnfBBmhKkfOarbiep/fyVJ1ACmWF9iN3jsaUQ4ItvwLJOENo2FmCOIlN0Cw7dj5
V8NSkqrnCXh/cp9DTTrwu2J5ljUwVvrYIcU3783ydr4zYY2CWwffklLw/jLR+9MK4xfK+D
foVru7s60M1n5PqkrluAehDmAbfEQ8H6GURD9wSLfrG2+1itVFTSpxCgIQdzdg+hybZ7ZI
wc/oMKiPPMtNObHDQ/lr9ssONQJiBGsmmaXgApTFCqUchv3svzNeXVYyF/iZq2HYTVM8bb
1oq1Rh7saBK4Ccc9URAAABAQCe/6eyVzXm/Lc71VfLjY9/8Gxs8zod3Ge1lurbAeT7qgzH
pwOXUW9Aahdun93nosYTdr4sJ8hbktBYMVlIQKxsfUIDS6z0Wk653PrNFzPwjSMKOppLQl
C7HKDqYtbOSRu0qP+vJ7Vw5cHPhU9k5doG2W9wKZUIByoGC4GAPLjV9HCedBhGtUc7qJT5
ezsHZ3Z6zr52WwL2kZW2DXgEjLYJMKxsJlsXLzFk7lK4MOAi2oA4rqFq3LJetDUDNg1HuJ
RTNmG4QezGDWfbU3OdCAVKswcik6S6q/KZDjKrtLwd1ub/6PAdxhLklso4+FYe+mfXv1tP
ANEP/nLRPObrHwuEAAABAQD88emqA+fjAWoBaWr+BmomaH9nF1OAL3wZyeaEZ69gv5KqFy
FWtmtmiGuvGUTsMsLDfoktKpHxhWY8kT6u16fYQTC1OFMrQA38S04RD5Y922l6DHATMZMQ
adMBkdAj5tQIwa/TTm2mhozUTtUgCOF6eIyJlwCRxDflB1CU2LracOKhiwxEibTorEH5oP
NomsVTQSiAB1DFqNh+anG9SEOsPWsOIAmDG2ztVXe5w0OCoayDKt7A1X+B2JqCyjGrhUrH
uTXnuIOhcenxGEaO897brA4fC4IxPT7cqi+ntREViryKZ9f0mkFyDUWGmPYOuqUVhkHryz
FFcFywQCU789HrAAABAQDmDuYJZC3P3jzPLDHYoieRw2ik62RDQER9beyDlwE4wG74QAg9
t/QG/5X0Ie3elmJQ32d8GaPJa8t5gsHxEl5mzU1mUu9payWYrM+ALHiL3icnF//KQ6Ovt7
+wN1WQ7gkiph/katY6Y4mmZXg7DccPyi+4c6BXWXTYHFQCN4d70EqRaNho4fGcyOZqGmJi
Qlv4EupRQOvcXUGt4tFJFq7YOszrGomzFq75esAaETuX/aDJjBU+X2gNi4CIc1UQICj1NM
s2GqXimetqFU4T55++H5fxjdOL4WmVnJ77wBOGxIo4EPHipjzm5wEzD9cD0GuBttVvgJF0
MDA3o/yFH+PvAAAAEmFuaWJha2E5QGdtYWlsLmNvbQ==
-----END OPENSSH PRIVATE KEY-----"


stages:
  - bundle
  - release_generated_build

bundle:
  stage: bundle
  image: node:9.0.0
  script:
    # Install ssh-agent through openssh-client if not present
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    # Add the private key to this user
    - eval $(ssh-agent -s) && ssh-add <(echo "$DEPLOY_PRIVATE_KEY") && mkdir -p ~/.ssh
    - yarn
    - yarn build
    - mkdir temp
    - cd temp && git clone git@gitlab.com:anibaka/tets-repo.git
    - cd tets-repo && cp -r ../../dist .
    - git config user.email "anibaka9@gmail.com"
    - git config user.name "anibaka"
    - git add .
    - git commit -am "test push"
    - git push origin master
  artifacts:
    paths:
    - ./dist