stages:
  - bundle
  - release_generated_build

bundle:
  stage: bundle
  image: node:9.0.0
  script:
    - yarn
    - yarn build
    - mkdir temp/
    - cd temp && cp -r ../dist .
    - ll
  artifacts:
    paths:
    - ./dist