import { Head, Data } from './index.types'
import nanoid from 'nanoid'

export const mock: { head: Head[]; data: Data } = {
  head: [
    { id: nanoid(), isNumber: true, label: 'Coin' },
    { id: nanoid(), isNumber: true, label: 'Coin' },
    { id: nanoid(), isNumber: true, label: 'Coin' },
  ],
  data: {
    body: [
      {
        id: '1',
        coin: { render: '1', style: { color: 'red' } },
        coen: 2,
        coan: 3,
      },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: '2', coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      {
        coin: 1,
        id: 'e',
        coen: 2,
        coan: 3,
      },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: nanoid(), coin: 1, coen: 2, coan: 3 },
      { id: ' 4', coin: 1, coen: 2, coan: 3 },
    ],
    footer: [
      {
        id: ' 1',
        coin: { render: '1', style: { color: 'green' }, isNumber: false },
        coen: 2,
        coan: 3,
        options: {
          variant: 'body',
          static: true,
        },
      },
      { id: '2', coin: 1, coen: 2, coan: 3 },
      { id: ' 4', coin: 1, coen: 2, coan: 3 },
    ],
  },
}
