export const data = {
  industry: [
    { label: 'Smart Contracts', value: 'smartContracts' },
    { label: 'Payments', value: 'payments' },
    { label: 'Blockchain Platform', value: 'blockchain' },
    { label: 'Payment Coin', value: 'paymentCoin' },
    { label: 'Privacy Coin', value: 'privacyCoin' },
    {
      label: 'Third Generation Blockchain',
      value: 'thirdGenerationBlockchain',
    },
    {
      label: 'Scalable Blockchain as a Service Platform',
      value: 'scalableBlockchain',
    },
  ],
  timeInterval: [
    { label: '1 Minute', value: '1minute' },
    { label: '5 Minutes', value: '5minutes' },
    { label: '15 Minutes', value: '15minutes' },
    { label: '1 Hour', value: '1hour' },
    { label: '4 Hour', value: '4hour' },
    { label: '1 Day', value: '1day' },
    { label: '1 Week', value: '1week' },
  ],
  marketCap: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  averageVolume10: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  averageVolume30: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  averageVolume60: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  averageVolume90: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  averageVolumeOnBalance: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  changeInPercentage: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  closingPriceAverage: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  simpleMovingAverage: [
    { label: 'Below', value: 'valueBelow' },
    { label: 'Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Above', value: 'valueAbove' },
    { label: 'Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Equals To', value: 'valueEqualsTo' },
    { label: 'Not Equal To', value: 'valueNotEqualTo' },
    { label: 'Crosses', value: 'crosses' },
    { label: 'Cross Up', value: 'crossUp' },
    { label: 'Cross Down', value: 'crossUp' },
  ],
  low: [
    { label: '1 Hour Low', value: 'one1HourLow' },
    { label: '1 Day Low', value: 'one1DayLow' },
    { label: '1 Month Low', value: 'one1MonthLow' },
    { label: '3 Month Low', value: 'three3MonthLow' },
    { label: '12 Month Low', value: 'twelve12MonthLow' },
    { label: 'All time Low', value: 'allTimeLow' },
  ],
  high: [
    { label: '1 Hour High', value: 'one1HourHigh' },
    { label: '1 Day High', value: 'one1DayHigh' },
    { label: '1 Month High', value: 'one1MonthHigh' },
    { label: '3 Month High', value: 'three3MonthHigh' },
    { label: '12 Month High', value: 'twelve12MonthHigh' },
    { label: 'All time High', value: 'allTimeHigh' },
  ],
}
